import { Request, Response } from "express";
import Organization from "../models/Organization";
import OrganizationMember from "../models/OrganizationMember";
import Term from "../models/Term";
import ClearanceRequest from "../models/ClearanceRequest";
import { logAudit } from "../utils/auditLogger";
import mongoose from "mongoose";
import { AppError, catchAsync } from "../utils/errors";

const resolveInstitutionId = (req: Request) => {
  const user = (req as any).user;
  if (!user) return null;
  if (user.role === 'super_admin') {
    return req.query.institutionId || req.body.institutionId || user.institutionId;
  }
  return user.institutionId;
};

/**
 * Creates a new organization within an institution.
 * Role: Institution Admin, Super Admin
 */
export const createOrganization = catchAsync(async (req: Request, res: Response) => {
    let { name, description, termId, code, signatoryName, isActive, order, isFinal } = req.body;
    const institutionId = resolveInstitutionId(req);
    const creatorId = (req as any).user?.id;

    console.log(`[ORG_CREATE] Attempting to create organization: "${name}" for institution: ${institutionId}`);

    if (!name) {
        throw new AppError("Organization name is required.", 400);
    }

    if (!institutionId) {
        throw new AppError("Institution context is required.", 401);
    }

    // 1. Resolve termId if not provided (Automatic Fallback)
    if (!termId) {
        console.log(`[ORG_CREATE] No termId provided, searching for active term...`);
        const activeTerm = await Term.findOne({ institutionId, isActive: true });
        if (activeTerm) {
            termId = activeTerm._id;
            console.log(`[ORG_CREATE] Using active term: ${activeTerm.academicYear} ${activeTerm.semester}`);
        } else {
            console.log(`[ORG_CREATE] No active term found, falling back to latest term...`);
            const latestTerm = await Term.findOne({ institutionId }).sort({ academicYear: -1, semester: -1 });
            if (latestTerm) {
                termId = latestTerm._id;
                console.log(`[ORG_CREATE] Using latest fallback term: ${latestTerm.academicYear} ${latestTerm.semester}`);
            } else {
                throw new AppError("No academic term found. Please create a Term first in System Settings.", 400);
            }
        }
    } else {
        // Verify provided termId
        const term = await Term.findOne({ _id: termId, institutionId });
        if (!term) {
            throw new AppError("Invalid term for this institution.", 400);
        }
    }

    // 2. Create the Organization
    // The joinCode is automatically generated by the model's default function
    const newOrg = await Organization.create({
        name,
        description,
        institutionId,
        termId,
        code,
        signatoryName,
        isActive: isActive !== undefined ? isActive : true,
        order: order || 0,
        isFinal: isFinal || false,
        createdBy: creatorId,
        status: "active"
    });

    // 3. Automatically add the creator as an 'officer' member
    await OrganizationMember.create({
        organizationId: newOrg._id,
        userId: creatorId,
        institutionId,
        role: "officer",
        status: "active",
        joinedAt: new Date()
    });

    // 4. Log the action
    await logAudit({
        userId: creatorId,
        institutionId,
        action: 'ORGANIZATION_CREATED',
        category: 'organization_management',
        resource: 'Organization',
        resourceId: newOrg._id as any,
        details: {
            name: newOrg.name,
            termId: newOrg.termId,
            joinCode: newOrg.joinCode
        },
        severity: 'medium',
        req
    });

    res.status(201).json({
        status: 'success',
        message: "Organization created successfully.",
        organization: newOrg
    });
});

/**
 * Get all organizations for the current institution
 */
export const getInstitutionOrganizations = catchAsync(async (req: Request, res: Response) => {
    const institutionId = resolveInstitutionId(req);
    if (!institutionId) throw new AppError("Institution context is required.", 401);

    const [organizations, activeTerm] = await Promise.all([
        Organization.find({ institutionId, status: 'active' })
            .populate('termId', 'name academicYear semester')
            .sort({ order: 1, createdAt: -1 }),
        Term.findOne({ institutionId, isActive: true })
    ]);

    const processedOrgs = organizations.map(org => {
        const orgObj = org.toObject() as any;
        if (!orgObj.termId && activeTerm) {
            const term: any = activeTerm;
            orgObj.termId = {
                _id: term._id,
                name: term.name,
                academicYear: term.academicYear,
                semester: term.semester
            };
        }
        return orgObj;
    });

    res.json({ status: 'success', organizations: processedOrgs });
});

/**
 * Get all deleted (archived) organizations for the institution
 */
export const getDeletedOrganizations = catchAsync(async (req: Request, res: Response) => {
    const institutionId = resolveInstitutionId(req);
    if (!institutionId) throw new AppError("Institution context is required.", 401);

    const organizations = await Organization.find({ institutionId, status: 'archived' })
        .populate('termId', 'name academicYear semester')
        .sort({ updatedAt: -1 });

    res.json({ status: 'success', organizations });
});

/**
 * Update an organization
 */
export const updateOrganization = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const institutionId = resolveInstitutionId(req);
    const updateData = req.body;

    const organization = await Organization.findOneAndUpdate(
        { _id: organizationId, institutionId },
        updateData,
        { new: true, runValidators: true }
    );

    if (!organization) throw new AppError("Organization not found.", 404);

    res.json({ status: 'success', organization });
});

/**
 * Update organization appearance (Officers only)
 */
export const updateOrganizationAppearance = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const userId = (req as any).user?.id;
    const institutionId = resolveInstitutionId(req);
    const { themeColor, headerImage } = req.body;

    // 1. Verify officer status
    const officerMember = await OrganizationMember.findOne({
        organizationId,
        userId,
        role: "officer",
        status: "active"
    });

    const isAdmin = (req as any).user?.role === 'admin' || (req as any).user?.role === 'super_admin';

    if (!officerMember && !isAdmin) {
        throw new AppError("You don't have permission to customize this organization's appearance.", 403);
    }

    // 2. Update
    const organization = await Organization.findOneAndUpdate(
        { _id: organizationId, institutionId },
        { themeColor, headerImage },
        { new: true, runValidators: true }
    );

    if (!organization) throw new AppError("Organization not found.", 404);

    res.json({ status: 'success', organization });
});

/**
 * Restore an archived organization
 */
export const restoreOrganization = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const institutionId = resolveInstitutionId(req);
    const userId = (req as any).user?.id;
    const userRole = (req as any).user?.role;

    let isAuthorized = userRole === 'admin' || userRole === 'super_admin';
    if (!isAuthorized) {
        const membership = await OrganizationMember.findOne({
            organizationId,
            userId,
            status: 'active'
        });
        if (membership) isAuthorized = true;
    }

    if (!isAuthorized) {
        throw new AppError("You don't have permission to restore this organization.", 403);
    }

    const organization = await Organization.findOneAndUpdate(
        { _id: organizationId, institutionId },
        { status: 'active' },
        { new: true }
    );

    if (!organization) throw new AppError("Organization not found.", 404);

    res.json({ status: 'success', organization });
});

/**
 * Permanently delete an organization
 */
export const permanentDeleteOrganization = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const institutionId = resolveInstitutionId(req);

    const organization = await Organization.findOneAndDelete({ _id: organizationId, institutionId });

    if (!organization) throw new AppError("Organization not found.", 404);

    // Clean up related data to prevent orphaned records/crashes
    await Promise.all([
        OrganizationMember.deleteMany({ organizationId }),
        ClearanceRequest.deleteMany({ organizationId })
    ]);

    res.json({ status: 'success', message: "Organization and all related records permanently deleted." });
});

/**
 * Join an organization using a unique join code.
 * Rules:
 * - Must belong to the same institution.
 * - Prevents duplicate membership.
 */
export const joinOrganization = catchAsync(async (req: Request, res: Response) => {
    const { joinCode } = req.body;
    const userId = (req as any).user?.id;
    const institutionId = resolveInstitutionId(req);

    if (!joinCode) {
        throw new AppError("Join code is required.", 400);
    }

    if (!institutionId) {
        throw new AppError("Institution context is required.", 401);
    }

    console.log(`[DEBUG] joinOrganization reg.body:`, JSON.stringify(req.body));
    console.log(`[DEBUG] joinOrganization user context:`, { userId, institutionId });
    const processedCode = (joinCode || "").toString().toUpperCase().trim();
    console.log(`[DEBUG] joinOrganization processedCode: '${processedCode}'`);

    // 1. Try finding by JUST joinCode first to see if it even exists
    const orgByCode = await Organization.findOne({ joinCode: processedCode });
    console.log(`[DEBUG] Step 1: findOne({ joinCode: '${processedCode}' }) ->`, orgByCode ? `Found (${orgByCode.name})` : 'NOT FOUND');

    if (orgByCode) {
        console.log(`[DEBUG] Step 1 Details:`, {
            id: orgByCode._id,
            instId: orgByCode.institutionId.toString(),
            userInstId: institutionId.toString(),
            status: orgByCode.status,
            isActive: orgByCode.isActive,
            match: orgByCode.institutionId.toString() === institutionId.toString()
        });
    }

    // 2. The actual restrictive query
    const organization = await Organization.findOne({
        joinCode: processedCode,
        institutionId: institutionId // Force match on institution
    });

    console.log(`[DEBUG] Step 2: findOne({ joinCode, institutionId }) ->`, organization ? 'Found' : 'NOT FOUND');

    if (!organization || organization.status !== 'active' || !organization.isActive) {
        console.log(`[DEBUG] Rejecting join request. Reason:`, !organization ? 'Org not found for this inst' : (organization.status !== 'active' ? 'Status not active' : 'isActive is false'));
        throw new AppError("Invalid join code. Organization not found.", 404);
    }

    // 2. Multi-tenant Check: Ensure organization belongs to the user's institution
    if (organization.institutionId.toString() !== institutionId.toString()) {
        // Log security event: Attempt to join org from different institution
        await logAudit({
            userId,
            institutionId,
            action: 'CROSS_INSTITUTION_JOIN_ATTEMPT',
            category: 'system',
            resource: 'Organization',
            resourceId: organization._id as any,
            details: {
                joinCode,
                targetInstitutionId: organization.institutionId
            },
            severity: 'high',
            req
        });

        throw new AppError("Access Denied. This organization belongs to another institution.", 403);
    }

    // 3. Check for existing member (ANY status)
    const existingMember = await OrganizationMember.findOne({
        organizationId: organization._id,
        userId
    });

    if (existingMember && existingMember.status === 'active') {
        throw new AppError("You are already a member of this organization.", 400);
    }

    // 4. Create or Reactivate Membership Record
    const membership = await OrganizationMember.findOneAndUpdate(
        { organizationId: organization._id, userId },
        {
            institutionId,
            role: "member", // Default role when joining via code
            status: "active",
            joinedAt: new Date(),
            statusChangedAt: new Date()
        },
        { upsert: true, new: true, runValidators: true }
    );

    // 5. AUTOMATICALLY START CLEARANCE WORKFLOW
    // Only for students/members. This creates the ClearanceRequest model 
    // needed for submitting requirements.
    const activeTerm = await Term.findOne({ institutionId, isActive: true });
    if (activeTerm) {
        try {
            // Check if already exists for this term
            const existingRequest = await ClearanceRequest.findOne({
                userId,
                organizationId: organization._id,
                termId: activeTerm._id
            });

            if (!existingRequest) {
                await ClearanceRequest.create({
                    userId,
                    organizationId: organization._id,
                    institutionId,
                    termId: activeTerm._id,
                    status: "in_progress", // Start as in_progress immediately
                    submittedAt: new Date()
                });
                console.log(`[DEBUG] Automatically started clearance for user ${userId} in org ${organization.name}`);
            }
        } catch (err) {
            console.error("[ERROR] Failed to auto-start clearance on join:", err);
            // We don't throw here to avoid blocking the join process if term/request fails
        }
    }

    // 6. Log Success
    await logAudit({
        userId,
        institutionId,
        action: 'ORGANIZATION_JOINED',
        category: 'organization_management',
        resource: 'Organization',
        resourceId: organization._id as any,
        details: {
            name: organization.name,
            joinCode: organization.joinCode
        },
        severity: 'low',
        req
    });

    res.status(200).json({
        status: 'success',
        message: "Successfully joined the organization.",
        organization: {
            id: organization._id,
            name: organization.name,
            description: organization.description
        },
        membership
    });
});

/**
 * Leave an organization.
 * Role: Member, Officer
 */
export const leaveOrganization = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const userId = (req as any).user?.id;
    const institutionId = resolveInstitutionId(req);

    const membership = await OrganizationMember.findOne({
        organizationId,
        userId,
        status: "active"
    });

    if (!membership) {
        throw new AppError("Active membership not found for this organization.", 404);
    }

    membership.status = "left";
    membership.statusChangedAt = new Date();
    await membership.save();

    await logAudit({
        userId,
        institutionId,
        action: 'MEMBERSHIP_LEFT',
        category: 'organization_management',
        resource: 'Organization',
        resourceId: new mongoose.Types.ObjectId(organizationId),
        severity: 'low',
        req
    });

    res.json({ status: 'success', message: "You have successfully left the organization." });
});

/**
 * Remove a member from an organization.
 * Role: Officer (of the org), Institution Admin, Super Admin
 */
export const removeMember = catchAsync(async (req: Request, res: Response) => {
    const { organizationId, targetUserId } = req.body;
    const adminId = (req as any).user?.id;
    const adminRole = (req as any).user?.role;
    const institutionId = resolveInstitutionId(req);

    if (!organizationId || !targetUserId) {
        throw new AppError("Organization ID and Target User ID are required.", 400);
    }

    // 1. Permission Check
    let isAuthorized = adminRole === 'super_admin' || adminRole === 'admin';

    if (!isAuthorized) {
        // Check if requester is an officer in this specific organization
        const officerMember = await OrganizationMember.findOne({
            organizationId,
            userId: adminId,
            role: "officer",
            status: "active"
        });
        if (officerMember) isAuthorized = true;
    }

    if (!isAuthorized) {
        throw new AppError("You don't have permission to remove members from this organization.", 403);
    }

    // 2. Perform Removal
    const membership = await OrganizationMember.findOne({
        organizationId,
        userId: targetUserId,
        status: "active"
    });

    if (!membership) {
        throw new AppError("Active membership not found for this user in this organization.", 404);
    }

    membership.status = "removed";
    membership.statusChangedAt = new Date();
    await membership.save();

    // 3. Log
    await logAudit({
        userId: adminId,
        institutionId,
        action: 'MEMBERSHIP_REMOVED',
        category: 'organization_management',
        resource: 'Organization',
        resourceId: new mongoose.Types.ObjectId(organizationId),
        details: { removedUserId: targetUserId },
        severity: 'medium',
        req
    });

    res.json({ status: 'success', message: "Member successfully removed from the organization." });
});

/**
 * Get details for a single organization.
 * Includes user's membership status.
 */
export const getOrganizationDetails = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const userId = (req as any).user?.id;
    const institutionId = resolveInstitutionId(req);

    if (!mongoose.Types.ObjectId.isValid(organizationId)) {
        throw new AppError("Invalid organization ID.", 400);
    }

    // 1. Fetch Organization
    const organization = await Organization.findOne({
        _id: organizationId,
        institutionId
    }).populate('termId', 'name academicYear semester');

    if (!organization) {
        throw new AppError("Organization not found.", 404);
    }

    // 2. Fetch User Membership
    const membership = await OrganizationMember.findOne({
        organizationId,
        userId,
        status: 'active'
    });

    res.json({
        status: 'success',
        organization,
        membership: membership ? {
            role: membership.role,
            joinedAt: membership.joinedAt
        } : null
    });
});

/**
 * Archive an organization.
 * Role: Institution Admin, Super Admin
 */
export const archiveOrganization = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const institutionId = resolveInstitutionId(req);
    const userId = (req as any).user?.id;
    const userRole = (req as any).user?.role;

    let isAuthorized = userRole === 'admin' || userRole === 'super_admin';
    if (!isAuthorized) {
        const membership = await OrganizationMember.findOne({
            organizationId,
            userId,
            status: 'active'
        });
        if (membership) isAuthorized = true;
    }

    if (!isAuthorized) {
        throw new AppError("You don't have permission to archive this organization.", 403);
    }

    const organization = await Organization.findOne({
        _id: organizationId,
        institutionId
    });

    if (!organization) {
        throw new AppError("Organization not found.", 404);
    }

    organization.status = 'archived';
    await organization.save();

    await logAudit({
        userId,
        institutionId,
        action: 'ORGANIZATION_ARCHIVED',
        category: 'organization_management',
        resource: 'Organization',
        resourceId: organization._id as any,
        details: { name: organization.name },
        severity: 'medium',
        req
    });

    res.json({
        status: 'success',
        message: "Organization archived successfully.",
        organization
    });
});

/**
 * Get all members of an organization.
 * Role: Officer of the org, Institution Admin, Super Admin
 */
export const getOrganizationMembers = catchAsync(async (req: Request, res: Response) => {
    const { organizationId } = req.params;
    const institutionId = resolveInstitutionId(req);
    const userId = (req as any).user?.id;
    const userRole = (req as any).user?.role;

    // 1. Permission Check
    let isAuthorized = userRole === 'super_admin' || userRole === 'admin';

    if (!isAuthorized) {
        // Any active member of the organization can view the members list
        const membership = await OrganizationMember.findOne({
            organizationId,
            userId,
            status: "active"
        });
        if (membership) isAuthorized = true;
    }

    if (!isAuthorized) {
        throw new AppError("You don't have permission to view this organization's members.", 403);
    }

    // 2. Fetch Members
    const members = await OrganizationMember.find({
        organizationId,
        status: 'active'
    })
        .populate('userId', 'fullName email studentId role enabled avatarUrl')
        .sort({ joinedAt: 1 });

    res.json({
        status: 'success',
        results: members.length,
        data: members
    });
});

/**
 * Get all terms for the current institution.
 */
export const getTerms = catchAsync(async (req: Request, res: Response) => {
    const institutionId = resolveInstitutionId(req);

    if (!institutionId) {
        throw new AppError("Institution context is required.", 401);
    }

    const terms = await Term.find({ institutionId }).sort({ academicYear: -1, semester: -1 });

    res.json({
        status: 'success',
        results: terms.length,
        data: terms
    });
});

/**
 * Get all organizations the current user is a member of.
 */
export const getMyOrganizations = catchAsync(async (req: Request, res: Response) => {
    const userId = (req as any).user?.id;
    const institutionId = resolveInstitutionId(req);

    if (!userId || !institutionId) {
        throw new AppError("Authentication required.", 401);
    }

    const [memberships, activeTerm] = await Promise.all([
        OrganizationMember.find({
            userId,
            institutionId,
            status: 'active'
        }).populate({
            path: 'organizationId',
            populate: { path: 'termId', select: 'name academicYear semester' }
        }),
        Term.findOne({ institutionId, isActive: true })
    ]);

    const { includeArchived } = req.query;

    // CRITICAL FIX: Filter out memberships for organizations that have been deleted or archived.
    const validMemberships = memberships.filter(m => {
        if (m.organizationId === null) return false;
        if (includeArchived === 'true') return true;
        return (m.organizationId as any).status !== 'archived';
    });

    const organizations = validMemberships.map(m => {
        const org: any = m.organizationId;
        const orgObj = org.toObject() as any;

        // Smart Fallback: If organization has no termId, use the institution's active term
        if (!orgObj.termId && activeTerm) {
            const term: any = activeTerm;
            orgObj.termId = {
                _id: term._id,
                name: term.name,
                academicYear: term.academicYear,
                semester: term.semester
            };
        }

        return {
            ...orgObj,
            membership: {
                role: m.role,
                joinedAt: m.joinedAt
            }
        };
    });

    res.json({
        status: 'success',
        results: organizations.length,
        organizations
    });
});
